### ISSUE TITLE
URL is not parsed with params

### ISSUE THREAD

**Issue by askerrit** [bee-san/pyWhat#260]
```
$ pywhat https://google.com?pageId=102013
zsh: no matches found: https://google.com?pageId=102013
```

**Comment by newtoallofthis123** [comment]
It works quite well for me. I tried and tested the latest version of `pywhat` with about 100 randomly generated URI's with parameters. You can find the url's and output [here](https://noobscience.rocks/code/kmRoTm).

Since zsh couldn't find any matches, I would recommend you to do any of the following:

1. Check your zsh config: is pywhat being overridden by something
2. Check in a different terminal
3. Reinstall pywhat

Hope it helps....
